// AUTO-GENERATED from supabase/schema.sql by scripts/generate-schema-module.mjs.
// Do not edit by hand — edit the .sql file and re-run the script.

export const MOMENTUM_SCHEMA_SQL = `-- ===========================================================================
-- Momentum — Supabase schema, Row Level Security and auth wiring.
--
-- Run this ONCE in your Supabase project:
--   Dashboard → SQL Editor → New query → paste → Run
--
-- It is fully idempotent: re-running it never drops a table and never deletes
-- a single row. Existing data is preserved.
-- ===========================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------------

-- The two account seats. \`id\` always equals auth.users.id.
create table if not exists public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  slot          smallint not null,
  name          text not null,
  name_key      text not null,
  email         text not null,
  color         text not null default '#a3e635',
  seeded        boolean not null default false,
  settings      jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create unique index if not exists profiles_slot_key on public.profiles (slot);
create unique index if not exists profiles_name_key_key on public.profiles (name_key);
create unique index if not exists profiles_email_key on public.profiles (lower(email));

-- A seat is always one of the two real tracker positions. Add the constraint
-- separately so re-running this schema also upgrades projects created by an
-- earlier version.
do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'profiles_slot_check'
       and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_slot_check check (slot in (1, 2));
  end if;
end
$$;

create table if not exists public.habits (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  name        text not null,
  icon        text not null,
  color       text not null,
  sort_order  integer not null default 0,
  created_key text not null,
  created_at  timestamptz not null default now()
);
create index if not exists habits_user_idx on public.habits (user_id, sort_order);

create table if not exists public.habit_logs (
  user_id    uuid not null references public.profiles (id) on delete cascade,
  habit_id   bigint not null references public.habits (id) on delete cascade,
  date       text not null,
  status     text not null check (status in ('completed', 'skipped')),
  updated_at timestamptz not null default now(),
  primary key (user_id, habit_id, date)
);
create index if not exists habit_logs_user_date_idx on public.habit_logs (user_id, date);

create table if not exists public.wallet_txns (
  id         text primary key,
  user_id    uuid not null references public.profiles (id) on delete cascade,
  name       text not null,
  category   text not null,
  amount     numeric(14, 2) not null,
  type       text not null check (type in ('income', 'expense')),
  date       text not null,
  created_at bigint not null
);
create index if not exists wallet_user_idx on public.wallet_txns (user_id, created_at desc);

create table if not exists public.xp_events (
  user_id uuid not null references public.profiles (id) on delete cascade,
  key     text not null,
  label   text not null,
  amount  integer not null,
  day     text not null,
  at_ms   bigint not null,
  primary key (user_id, key)
);
create index if not exists xp_events_user_at_idx on public.xp_events (user_id, at_ms);

create table if not exists public.progress_state (
  user_id    uuid primary key references public.profiles (id) on delete cascade,
  total_xp   bigint not null default 0,
  level      integer not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.quest_claims (
  user_id     uuid not null references public.profiles (id) on delete cascade,
  event_key   text not null,
  quest_id    text not null,
  period_key  text not null,
  xp_awarded  integer not null,
  claimed_at  bigint not null,
  primary key (user_id, event_key)
);

create table if not exists public.achievements (
  user_id        uuid not null references public.profiles (id) on delete cascade,
  achievement_id text not null,
  unlocked_at    bigint not null,
  metadata       jsonb not null default '{}'::jsonb,
  primary key (user_id, achievement_id)
);

-- ---------------------------------------------------------------------------
-- 2. Exactly two seats + automatic profile creation on sign-up
-- ---------------------------------------------------------------------------

create or replace function public.momentum_handle_new_user()
returns trigger
language plpgsql
security definer
-- An empty search_path is the hardened Supabase recommendation: every object
-- below is schema-qualified, so nothing can be shadowed by a temp object.
set search_path = ''
as $$
declare
  seat_count int;
  next_slot  int;
  meta_name  text;
  meta_color text;
begin
  -- Serialize seat claims. Without this lock, two simultaneous signups could
  -- both observe the same free slot and one would fail on the unique index.
  perform pg_advisory_xact_lock(hashtext('momentum-account-seats'));

  -- If a profile already exists for this auth user, do nothing.
  if exists (select 1 from public.profiles p where p.id = new.id) then
    return new;
  end if;

  select count(*) into seat_count from public.profiles;
  if seat_count >= 2 then
    raise exception 'MOMENTUM_FULL: this tracker only has two seats';
  end if;

  -- Fill the lowest available real seat. This also handles removing seat 1
  -- while seat 2 remains, instead of incorrectly attempting to create slot 3.
  select candidate.slot
    into next_slot
    from (values (1), (2)) as candidate(slot)
   where not exists (
     select 1 from public.profiles p where p.slot = candidate.slot
   )
   order by candidate.slot
   limit 1;

  if next_slot is null then
    raise exception 'MOMENTUM_FULL: this tracker only has two seats';
  end if;

  meta_name := nullif(btrim(coalesce(new.raw_user_meta_data ->> 'name', '')), '');
  if meta_name is null then
    meta_name := split_part(coalesce(new.email, 'Owner'), '@', 1);
  end if;

  meta_color := coalesce(new.raw_user_meta_data ->> 'color', '');
  if meta_color !~ '^#[0-9a-fA-F]{6}$' then
    meta_color := case when next_slot = 1 then '#a3e635' else '#38bdf8' end;
  end if;

  insert into public.profiles (id, slot, name, name_key, email, color)
  values (
    new.id,
    next_slot,
    meta_name,
    lower(regexp_replace(meta_name, '\\s+', ' ', 'g')),
    coalesce(new.email, ''),
    lower(meta_color)
  );

  insert into public.progress_state (user_id, total_xp, level)
  values (new.id, 0, 1)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists momentum_on_auth_user_created on auth.users;
create trigger momentum_on_auth_user_created
  after insert on auth.users
  for each row execute function public.momentum_handle_new_user();

-- Keep e-mail in sync if it is ever changed in Supabase Auth.
create or replace function public.momentum_sync_user_email()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.profiles
     set email = coalesce(new.email, email), updated_at = now()
   where id = new.id;
  return new;
end;
$$;

drop trigger if exists momentum_on_auth_user_updated on auth.users;
create trigger momentum_on_auth_user_updated
  after update of email on auth.users
  for each row execute function public.momentum_sync_user_email();

-- Hard cap: a third profile row can never be written, whatever the path.
create or replace function public.momentum_enforce_two_seats()
returns trigger
language plpgsql
-- Pinning search_path clears the Supabase "Function Search Path Mutable" warning.
set search_path = ''
as $$
begin
  perform pg_advisory_xact_lock(hashtext('momentum-account-seats'));
  if new.slot not in (1, 2) then
    raise exception 'MOMENTUM_INVALID_SEAT: slot must be 1 or 2';
  end if;
  if (select count(*) from public.profiles) >= 2 then
    raise exception 'MOMENTUM_FULL: this tracker only has two seats';
  end if;
  return new;
end;
$$;

drop trigger if exists momentum_profiles_seat_cap on public.profiles;
create trigger momentum_profiles_seat_cap
  before insert on public.profiles
  for each row execute function public.momentum_enforce_two_seats();

-- ---------------------------------------------------------------------------
-- 3. Row Level Security
--    • Private by owner : wallet_txns, quest_claims, achievements, profiles
--    • Shared read-only : habits, habit_logs, xp_events, progress_state
--      (the partner consistency card + the Level/XP comparison need these;
--       writes are still restricted to the row owner)
-- ---------------------------------------------------------------------------

alter table public.profiles       enable row level security;
alter table public.habits         enable row level security;
alter table public.habit_logs     enable row level security;
alter table public.wallet_txns    enable row level security;
alter table public.xp_events      enable row level security;
alter table public.progress_state enable row level security;
alter table public.quest_claims   enable row level security;
alter table public.achievements   enable row level security;

-- profiles -------------------------------------------------------------------
-- Rows are visible to the seat picker (anon) and to the signed-in partner, but
-- only through the column privileges granted in section 6: \`email\`, \`name_key\`
-- and \`settings\` are never readable by anyone over the API. This replaces the
-- old SECURITY DEFINER views, which triggered Supabase Security Advisor
-- "Security Definer View" warnings.
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public" on public.profiles
  for select to anon, authenticated using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
  for insert to authenticated with check (id = (select auth.uid()));

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

-- habits ---------------------------------------------------------------------
drop policy if exists "habits_select_shared" on public.habits;
create policy "habits_select_shared" on public.habits
  for select to authenticated using (true);

drop policy if exists "habits_insert_own" on public.habits;
create policy "habits_insert_own" on public.habits
  for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "habits_update_own" on public.habits;
create policy "habits_update_own" on public.habits
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "habits_delete_own" on public.habits;
create policy "habits_delete_own" on public.habits
  for delete to authenticated using (user_id = (select auth.uid()));

-- habit_logs -----------------------------------------------------------------
drop policy if exists "habit_logs_select_shared" on public.habit_logs;
create policy "habit_logs_select_shared" on public.habit_logs
  for select to authenticated using (true);

drop policy if exists "habit_logs_insert_own" on public.habit_logs;
create policy "habit_logs_insert_own" on public.habit_logs
  for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "habit_logs_update_own" on public.habit_logs;
create policy "habit_logs_update_own" on public.habit_logs
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "habit_logs_delete_own" on public.habit_logs;
create policy "habit_logs_delete_own" on public.habit_logs
  for delete to authenticated using (user_id = (select auth.uid()));

-- wallet_txns (strictly private: money is never shared) -----------------------
drop policy if exists "wallet_all_own" on public.wallet_txns;
create policy "wallet_all_own" on public.wallet_txns
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- xp_events ------------------------------------------------------------------
drop policy if exists "xp_events_select_shared" on public.xp_events;
create policy "xp_events_select_shared" on public.xp_events
  for select to authenticated using (true);

drop policy if exists "xp_events_insert_own" on public.xp_events;
create policy "xp_events_insert_own" on public.xp_events
  for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "xp_events_delete_own" on public.xp_events;
create policy "xp_events_delete_own" on public.xp_events
  for delete to authenticated using (user_id = (select auth.uid()));

-- progress_state -------------------------------------------------------------
drop policy if exists "progress_select_shared" on public.progress_state;
create policy "progress_select_shared" on public.progress_state
  for select to authenticated using (true);

drop policy if exists "progress_insert_own" on public.progress_state;
create policy "progress_insert_own" on public.progress_state
  for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "progress_update_own" on public.progress_state;
create policy "progress_update_own" on public.progress_state
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- quest_claims (private) ------------------------------------------------------
drop policy if exists "quests_all_own" on public.quest_claims;
create policy "quests_all_own" on public.quest_claims
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- achievements (private) ------------------------------------------------------
drop policy if exists "achievements_all_own" on public.achievements;
create policy "achievements_all_own" on public.achievements
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------------
-- 4. Controlled public / shared views
--    \`public_profiles\` powers the pre-login seat picker (names + colors only,
--    never emails). \`momentum_partner_progress\` is the shared Level/XP board.
-- ---------------------------------------------------------------------------

-- Both views run with \`security_invoker = true\`, so the caller's own RLS
-- policies and column privileges apply. Supabase Security Advisor therefore
-- reports no "Security Definer View" warning for this project.
drop view if exists public.public_profiles;
create view public.public_profiles
  with (security_invoker = true) as
  select id, slot, name, color, seeded
    from public.profiles;

drop view if exists public.momentum_partner_progress;
create view public.momentum_partner_progress
  with (security_invoker = true) as
  select p.id                          as user_id,
         p.slot                        as slot,
         p.name                        as name,
         p.color                       as color,
         coalesce(ps.total_xp, 0)      as total_xp,
         coalesce(ps.level, 1)         as level,
         ps.updated_at                 as updated_at
    from public.profiles p
    left join public.progress_state ps on ps.user_id = p.id;

revoke all on public.public_profiles from anon, authenticated;
revoke all on public.momentum_partner_progress from anon, authenticated;
grant select on public.public_profiles to anon, authenticated;
grant select on public.momentum_partner_progress to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Helper used after a backup restore so the identity stays ahead of ids
-- ---------------------------------------------------------------------------

create or replace function public.momentum_sync_habits_sequence()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  seq text;
begin
  seq := pg_get_serial_sequence('public.habits', 'id');
  if seq is not null then
    perform setval(seq, greatest((select coalesce(max(id), 1) from public.habits), 1));
  end if;
end;
$$;

grant execute on function public.momentum_sync_habits_sequence() to authenticated;

-- ---------------------------------------------------------------------------
-- 6. Table grants (RLS still decides every row)
-- ---------------------------------------------------------------------------

grant select, insert, update, delete on
  public.habits, public.habit_logs, public.wallet_txns,
  public.xp_events, public.progress_state, public.quest_claims,
  public.achievements
to authenticated;

-- profiles is column-restricted on purpose. \`email\`, \`name_key\` and \`settings\`
-- are NEVER selectable over the API — not even by the row's own owner, which
-- is safe because the address is always available from Supabase Auth itself.
revoke all on public.profiles from anon, authenticated;
grant select (id, slot, name, color, seeded, created_at, updated_at)
  on public.profiles to authenticated;
grant select (id, slot, name, color, seeded)
  on public.profiles to anon;
grant insert (id, slot, name, name_key, email, color)
  on public.profiles to authenticated;
grant update (name, color, seeded, settings, updated_at)
  on public.profiles to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- Anonymous visitors may only read the seat picker view.
revoke all on public.habits, public.habit_logs,
  public.wallet_txns, public.xp_events, public.progress_state,
  public.quest_claims, public.achievements from anon;

notify pgrst, 'reload schema';
`;
